services:
  livox-driver:
    build:
      context: ..  # 将构建上下文改为项目根目录
      dockerfile: on_g1/Dockerfile
    image: livox-ros-driver:latest
    container_name: on-g1
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - ./config:/catkin_ws/src/livox_ros_driver2/config
      - ./launch:/catkin_ws/src/livox_ros_driver2/launch
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
      - DISPLAY=${DISPLAY:-:0}
    stdin_open: true
    tty: true
    command: bash